version: '3'
services:
  app:
    build:
      context: .
    #  args:
        #UID: ${UID}
        #GID: ${GID}
    volumes:
      - /home/shinto/exercism/elixir:/exercism
    #command: mix run
    #entrypoint: ["-c", "sleep infinity"]

